### PR TITLE
Added more requirements to the readme

### PR DESCRIPTION
**Pull request by jetpacktuxedo**

### CODE REVIEW

**Comment by buhman** [comment]
Ehh, so these are build requirements, whereas the rest of the list are runtime requirements. This should really be a new `Build` section in the README (previously, pb had no build process).

Also, looks like I just grunt/curl asciienma-player, so no need to document that specially--and in particular, the dep would be `asciinema-player` anyway, not `asciinema`.

**Comment by jetpacktuxedo** [comment]
Alright, split it out into Build Requirements and Runtime Requirements, and also dumped out asciinema as a dependency.

For the record, asciinema-player doesn't seem to exist on ubuntu or debian. I think it is rolled into the base asciinema package, so that one package handles the recording as well as the playback.

**Comment by buhman** [comment]
> asciinema-player doesn't seem to exist on ubuntu or debian

It's a new thing (released 6 Jan 2016); I also doubt it's something they either would package to begin with.

> recording as well as the playback

This player is the js player--the terminal player just spits out the raw escapes at the right times and lets the terminal handle display.

> I split requirements out into Build Requirements and Runtime Requirements

Where?

**Comment by jetpacktuxedo** [comment]
Sorry, it is in the branch that this PR originated from. That usually updates the PR, but I guess it doesn't when it is closed. I will open a new PR for it though.

**Pull request closed without merging**
